In [1]:
#numpy(numerical python)is a python library which is used to perform different mathematical operations on arrays and matrices. It provides a powerful data structure called ndarray, which is a multidimensional array that can hold elements of the same data type.
#array is defnoted within square brackets and it is ordered,mutable and homogenous collection of elements.
import numpy as np

print(np.__version__)

2.3.5


In [3]:
#creating 1D array
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [2]:
a=np.array([1,2,3,4,5.7])
print(a)
type(a)

[1.  2.  3.  4.  5.7]


numpy.ndarray

In [6]:
a=np.array([1,2,3,4.5,5+7j])
print(a)
type(a)

[1. +0.j 2. +0.j 3. +0.j 4.5+0.j 5. +7.j]


numpy.ndarray

In [7]:
a=np.array([1,'2',3,4.5,5+7j])
print(a)
type(a)

['1' '2' '3' '4.5' '(5+7j)']


numpy.ndarray

In [8]:
#tuple to array
t=np.array((1,2,3,4,5))
print(t)
type(t)

[1 2 3 4 5]


numpy.ndarray

In [9]:
#set to array
s=np.array({1,2,3,4,5})
print(s)
type(s)


{1, 2, 3, 4, 5}


numpy.ndarray

In [31]:
#dictionary to array 
d=np.array({'name':'armaan','age':21})
print(d)
type(d)

{'name': 'armaan', 'age': 21}


numpy.ndarray

In [36]:
np.arange(1,7,2)

array([1, 3, 5])

In [37]:
np.zeros(4)

array([0., 0., 0., 0.])

In [32]:
#creating 2D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
#creating 2D array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape) #this gives the no.of rows and columns(row,col) in of a array.
print(a.size) #this gives the no of elements of array 
print(a.ndim) #this gives the dimention of array


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [34]:
b=np.array([[[1,2,3],[1,2,7]]])
print(b)
print(b.shape) 
print(b.size)  
print(b.ndim)
#d=np.array([1,2,3],ndmin=99) max 64D array can be made in my system

[[[1 2 3]
  [1 2 7]]]
(1, 2, 3)
6
3


In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
np.zeros((3,4),complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [45]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [48]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [55]:
np.linspace(0,100,10,dtype=int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [56]:
np.random.rand(4,5)

array([[0.02959123, 0.5930417 , 0.12933258, 0.50776883, 0.40262573],
       [0.72803117, 0.07365296, 0.69649376, 0.17655626, 0.08785091],
       [0.20161378, 0.01754599, 0.92672916, 0.39614857, 0.58949436],
       [0.94606765, 0.59947197, 0.3895509 , 0.65138596, 0.76003206]])

In [57]:
np.random.randint(1,100)

61

In [59]:
np.random.randint(1,100,(4,5))

array([[41, 58, 70, 89, 72],
       [85, 23, 65, 14, 76],
       [33, 25, 17, 35,  5],
       [29, 15, 92, 63, 10]], dtype=int32)

In [79]:
#mathematical operations using array
a=np.array([25,73,47])
b=np.array([43,33,53])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.divmod(a,b))
print(np.log(a))
print(np.sqrt(b))
print(np.cbrt(a))
print(np.power(a,b))
print(np.sin(a))
print(np.cos(b))
print(np.tan(a))
print(1/np.tan(a))


[ 68 106 100]
[-18  40  -6]
[1075 2409 2491]
[0.58139535 2.21212121 0.88679245]
[0 2 0]
[25  7 47]
(array([0, 2, 0]), array([25,  7, 47]))
[3.21887582 4.29045944 3.8501476 ]
[6.55743852 5.74456265 7.28010989]
[2.92401774 4.1793392  3.60882608]
[1791064955459420617 6785776024314768713 5166575435789760495]
[-0.13235175 -0.67677196  0.12357312]
[ 0.5551133  -0.01327675 -0.91828279]
[-0.13352641  0.9192864  -0.12452757]
[-7.48915531  1.08780027 -8.03035035]


In [114]:
#statistical functions
a=np.array([25,73,47,25])
print(np.max(a))
print(np.min(a))
print(np.argmax(a)) #gives the index value of max value of an array
print(np.argmin(a)) #gives the index value of min value of an array
print(np.sort(a))
print(np.argsort(a))
print(np.flip(a))
#print(flip(np.sort(a)))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.cumsum(a))
print(np.cumprod(a))
print(np.repeat(a,3))
print(np.tile(a,4))
print(np.where(a==25))
print(np.round(38.4))
print(np.round(38.6))
print(np.ceil(38.4)) #gives the higher round off value
print(np.trunc(38.9)) #gives the lower round off value

73
25
1
0
[25 25 47 73]
[0 3 2 1]
[25 47 73 25]
42.5
36.0
19.767397400770797
390.75
[ 25  98 145 170]
[     25    1825   85775 2144375]
[25 25 25 73 73 73 47 47 47 25 25 25]
[25 73 47 25 25 73 47 25 25 73 47 25 25 73 47 25]
(array([0, 3]),)
38.0
39.0
39.0
38.0


In [135]:
#vector mathematics
a=np.array([[1,2],[1,4]])
b=np.array([[3,7],[5,6],])
print('a=',a)
print('b=',b)

print('dot product=',np.dot(a,b))
print(a@b) #shortcut for dot product
print('cross product=',np.cross(a,b))
print(np.transpose(a))
print(a.T) #shortcut for transpose

a= [[1 2]
 [1 4]]
b= [[3 7]
 [5 6]]
dot product= [[13 19]
 [23 31]]
[[13 19]
 [23 31]]
cross product= [  1 -14]
[[1 1]
 [2 4]]
[[1 1]
 [2 4]]


C:\Users\mishr\AppData\Local\Temp\ipykernel_27112\3638699684.py:9: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print('cross product=',np.cross(a,b))


In [ ]:
a=np.array([25,16,28,71,90]) #1D array
print(a)
print(a[2]) #indexing is possible in all types of array
print(a[0:4:2]) # slicing is possible in all types of array

[25 16 28 71 90]
28
[25 28]


In [ ]:
a=np.random.randint(1,25,(5,5))
print(a)
print(a[0,2]) #indexing syntax:- var[row,col]
print(a[4,3])
print(a[3,::])
print(a[3:4:1,::])
print(a[3:4:1,1:4:1]) #var[row indexing,col indexing]
print('slicing',a[2:5:2,0:5:2]) #var[staring row: ending row+1: skip, starting col: ending col+1: skip]
print(a[2]) #prints the row 
np.where(a==3)

[[19  3 17 22 11]
 [ 4  9  3  2 14]
 [17 21  9 12  4]
 [ 8 13 22 11 13]
 [14 24  1  2  6]]
17
2
[ 8 13 22 11 13]
[[ 8 13 22 11 13]]
[[13 22 11]]
slicing [[17  9  4]
 [14  1  6]]
[17 21  9 12  4]


(array([0, 1]), array([1, 2]))

In [ ]:
a=np.random.randint(1,25,(5,5))
b=np.random.randint(1,20,(4,4))
c=np.random.randint(1,20,(4,4))
print('a=',a)                                      
print('b=',b)                            # axis 0  |
print('c=',c)                            #         |
# when vertically joined its in axis 0 (default)   | 
# when horizontally joined its in axis 1           |___________ axis 1
# when rows are same they are added vertically  # /
# when cols are same they are added horzontally #/  axis 2
print(np.concatenate(b,c))                     #/
print(np.hstack(a,b))
print(np.hstack(a,b))
print(np.vstack(a,b))



a= [[21  6 11 17 15]
 [14  2 10 24  6]
 [21 13 19 18  5]
 [ 4 10  5 17  5]
 [ 1 21  3 12  9]]
b= [[ 1  5  3  7]
 [ 7 12  5  6]
 [17 11  3 12]
 [ 5 10 14 19]]
c= [[16  9  6 11]
 [ 7 12 12 13]
 [ 7  6 17 15]
 [18 10  7 15]]


TypeError: only integer scalar arrays can be converted to a scalar index