<h2
>Natural Language Processing</h2>

It is of two types <pre>
1)NLU
2)NLG</PRE> 
It is done in two ways 
<pre>1)By Text
2)By Speech</pre>
Basic Terminologies in NLP :<pre>
1)Corpus- It is a large and structure set of text used for NLP.
2)Document- 
3)Words-
4)Vocabulary-
5)Vector-
6)Stopwords- 
7)Tokens- Piece of sentence or words</pre>
Steps Involved in NLP/Text Preprossing :<pre>
1)Tokenization- It is a process in which we convert big sentences into tokens of words,or a paragraph into tokens of single sentences.It is of two types 1) sent tonkeniser 2)word tokeniser 
2)Stemming-It is used to find the root or base words from spellings.(detail,details,deatailings)
3)Lemmatization-It is similar to stemmimg it is also used to find root words or base words from the different form of the words(go,went,gone).Output of lemmatization is a proper word.
4)POS Tags:It indicates how a word function in meaning as well as gramatically used within a sentence.(The cat killed the rat.)
5)Named Entity Recognition- It is used to identify weather it is a place, person, location etc.
6)Chunking- picking individual piece of information and grouping it into a bigger pieces is known as chunking.
 

In [11]:
import nltk
print(nltk.__version__)

3.9.2


In [12]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

Tokenisation

In [13]:
from nltk import sent_tokenize
sent_tokenize("this is a nlp example for tokenisation.converts words into tokens")

['this is a nlp example for tokenisation.converts words into tokens']

In [14]:
from nltk import word_tokenize
word_tokenize("this is a nlp example for tokenisation.converts words into tokens")

['this',
 'is',
 'a',
 'nlp',
 'example',
 'for',
 'tokenisation.converts',
 'words',
 'into',
 'tokens']

Stemming

In [15]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [16]:
ps.stem("guns")

'gun'

In [17]:
ps.stem("running")

'run'

In [18]:
ps.stem('happiness')

'happi'

In [19]:
ps.stem('armaan')

'armaan'

Lemmatization

In [20]:
from nltk.stem import WordNetLemmatizer
lm=WordNetLemmatizer()

In [21]:
lm.lemmatize('went','v')

'go'

In [22]:
lm.lemmatize('does','v')

'do'

In [23]:
lm.lemmatize('ate','v')

'eat'

In [24]:
lm.lemmatize('happiness','n')

'happiness'

In [25]:
lm.lemmatize('goodness','a')

'goodness'

In [26]:
lm.lemmatize('better','a')


'good'

In [23]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data]

True

In [27]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

POS Tags

In [28]:
t='mount everest is the highest mountain in the world'
print(t)

mount everest is the highest mountain in the world


In [29]:
t_tokens=word_tokenize(t)
t_tokens

['mount', 'everest', 'is', 'the', 'highest', 'mountain', 'in', 'the', 'world']

In [30]:
import nltk

nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [31]:
t_tag=nltk.pos_tag(t_tokens)
t_tag

[('mount', 'NN'),
 ('everest', 'NN'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('highest', 'JJS'),
 ('mountain', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('world', 'NN')]

In [32]:
tx='narendra modi is the prime minister of india since 2014'


In [33]:
import nltk

resources = [
    'punkt',
    'punkt_tab',
    'stopwords',
    'wordnet',
    'omw-1.4',
    'averaged_perceptron_tagger',
    'averaged_perceptron_tagger_eng',
    'maxent_ne_chunker',
    'maxent_ne_chunker_tab',
    'words',
    'vader_lexicon'
]

for r in resources:
    nltk.download(r)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mishr\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nl

In [34]:
from nltk import ne_chunk
tx_tag=ne_chunk(tx_tag)
tx_tag

NameError: name 'tx_tag' is not defined

Vectorization:It is used to identify the impotance of a word in a sentence it is of two types1)count vertoriser 2)TF-IDF vectoriser term frequency inverse document frequancy

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
txt=['I am learning Natural Language Processing','Natural Language Processing is interesting']
x=cv.fit_transform(txt)
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (2, 7)>

It takes the unique words from the sentences and create a sparse matrix.

In [36]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (2, 7)>
  Coords	Values
  (0, 0)	1
  (0, 4)	1
  (0, 5)	1
  (0, 3)	1
  (0, 6)	1
  (1, 5)	1
  (1, 3)	1
  (1, 6)	1
  (1, 2)	1
  (1, 1)	1


In [37]:
print(x.toarray())

[[1 0 0 1 1 1 1]
 [0 1 1 1 0 1 1]]


In [38]:
print(cv.vocabulary_)

{'am': 0, 'learning': 4, 'natural': 5, 'language': 3, 'processing': 6, 'is': 2, 'interesting': 1}


TF-IDF Vectorizer

It is defined as the number of times a word appear in a document/total no of words in the documnent

IDF Value:- It is the ratio of log of total no of document/ no fo documents the contains the word

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [40]:
txt=['l love singing and i love painting','i love ice-cream']
z=tfidf.fit_transform(txt)

In [41]:
z

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (2, 6)>

In [42]:
print(z)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (2, 6)>
  Coords	Values
  (0, 3)	0.6348087971775132
  (0, 5)	0.4461008073765536
  (0, 0)	0.4461008073765536
  (0, 4)	0.4461008073765536
  (1, 3)	0.4494364165239821
  (1, 2)	0.6316672017376245
  (1, 1)	0.6316672017376245


In [43]:
print(tfidf.vocabulary_)

{'love': 3, 'singing': 5, 'and': 0, 'painting': 4, 'ice': 2, 'cream': 1}


In [44]:
print(z.toarray())

[[0.44610081 0.         0.         0.6348088  0.44610081 0.44610081]
 [0.         0.6316672  0.6316672  0.44943642 0.         0.        ]]


In [45]:
from sklearn.datasets import fetch_20newsgroups

In [46]:
news=fetch_20newsgroups()

In [47]:
import numpy as np
import pandas as pd

In [48]:
np.unique(news.target)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
set(news.target)

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19)}

In [50]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [51]:
news_train=fetch_20newsgroups(subset='train')
news_test=fetch_20newsgroups(subset='test')

In [52]:
print(news_train.data[6])

From: bmdelane@quads.uchicago.edu (brian manning delaney)
Subject: Brain Tumor Treatment (thanks)
Reply-To: bmdelane@midway.uchicago.edu
Organization: University of Chicago
Lines: 12

There were a few people who responded to my request for info on
treatment for astrocytomas through email, whom I couldn't thank
directly because of mail-bouncing probs (Sean, Debra, and Sharon).  So
I thought I'd publicly thank everyone.

Thanks! 

(I'm sure glad I accidentally hit "rn" instead of "rm" when I was
trying to delete a file last September. "Hmmm... 'News?' What's
this?"....)

-Brian



In [53]:
print(news_test.data[6])

From: PETCH@gvg47.gvg.tek.com (Chuck)
Subject: Daily Verse
Lines: 3

Dishonest money dwindles away, but he who gathers money little by little makes
it grow. 
Proverbs 13:11



In [54]:
print(len(news_train.data))

11314


In [55]:
print(len(news_test.data))

7532


In [56]:
print(news_train.target[6])

13


In [57]:
a=fetch_20newsgroups(subset='all')
print(len(a.data))

18846


In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer,TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

In [59]:
model = Pipeline([
    ('vector', TfidfVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('algo', MultinomialNB())
])

In [60]:
model.fit(news_train.data,news_train.target)

,steps,"[('vector', ...), ('tfidf', ...), ...]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [62]:
def predict_category(s,tr=news_train,m=model):
    pred=m.predict([s])
    print(pred)
    return tr.target_names[pred[0]]

In [63]:
predict_category('audi is better than hyundai')

[7]


'rec.autos'

In [64]:
predict_category('the space shuttle is ready for launch')

[14]


'sci.space'

In [65]:
predict_category('he is our president')

[18]


'talk.politics.misc'